eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka
  instance:
    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
      isolation:
        thread:
          timeoutInMilliseconds: 5000
      circuitBreaker:
        enabled: true
        requestVolumeThreshold: 5   # 该属性设置滚动窗口中将使断路器跳闸的最小请求数量

management:
  server:
    port: 8001
  endpoint:
    health:
      show-details: always #显示熔断器详细信息 http://127.0.0.1:8001/actuator/health
    shutdown:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

#集群化监控配置
turbine:
  instanceUrlSuffix: /hystrix.stream  #没有的话会出现异常
  aggregator:
    clusterConfig: default
  appConfig: feign-consumer-group
  cluster-name-expression: "'default'"