server:
  port: 8000 #服务注册中心端口号

spring:
  application:
    name: eureka-server # 应用名称，会在Eureka中显示

eureka:
  client:
    registerWithEureka: false #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心位置
      defaultZone: http://127.0.0.1:8000/eureka/

